version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend-prueba
    ports:
      - "8088:8000"
    volumes:
    #funciona para proteger el codigo fuente del backend, ya que no se puede modificar desde el contenedor
      - ./backend:/usr/src/app/backend:ro
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: frontend-prueba
    ports:
      - "4321:4321"
    volumes:
    #esto es para que se pueda modificar el codigo fuente del frontend desde el contenedor ya que se crean archivos temporales
      - ./frontend:/usr/src/app/frontend
      #esto es para que no haya un choque de archivos
      - /usr/src/app/frontend/node_modules
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
      #para cuando cuando se trabaje con un entorno automatizado
      #- CI=true 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    restart: always
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - "8080:8080"
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin # Contraseña por defecto para entrar (el usuario es 'admin')
    depends_on:
    - prometheus
    restart: always

